Animal table
kamranasif506/Vet-Clinic pull request #1
Opened 2023-08-14 20:18 UTC by kamranasif506

In this PR

- Animal Table created in vet_clinic database
- Data inserted into animal table
- Following Quries run to fetch records
  - Find all animals whose name ends in "mon".
<img width="793" alt="Screenshot 2023-08-15 005430" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/53099ef6-2f2d-4496-8393-2c5162f97fda">

  - List the name of all animals born between 2016 and 2019.
<img width="791" alt="Screenshot 2023-08-15 005757" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/f7f29879-3f77-4a6c-8f5d-7d1887148b97">

  - List the name of all animals that are neutered and have less than 3 escape attempts.
<img width="791" alt="Screenshot 2023-08-15 010003" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/ec1a6f56-e1fb-4f5e-8929-d99ca6108ec2">

  - List the date of birth of all animals named either "Agumon" or "Pikachu".
<img width="789" alt="Screenshot 2023-08-15 011721" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/d0ce7a65-4f43-4560-8bd5-0c1525f92dfa">

  - List name and escape attempts of animals that weigh more than 10.5kg
<img width="791" alt="Screenshot 2023-08-15 010603" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/e3836cec-89ba-41f0-b4a8-e39ef0c004d1">

  - Find all animals that are neutered.
<img width="795" alt="Screenshot 2023-08-15 010701" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/db700645-db2e-4b5b-ae56-ba8926410b79">

  - Find all animals not named Gabumon.
<img width="797" alt="Screenshot 2023-08-15 010813" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/a861c508-892e-4f37-b9da-c5bc2f0b97c5">

  - Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)
<img width="790" alt="Screenshot 2023-08-15 011114" src="https://github.com/kamranasif506/Vet-Clinic/assets/98281453/23071e85-2dab-4614-b904-59e868184380">

2023-08-14 20:26 UTC, V-Blaze requested changes
Hi @kamranasif506 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![dcentl8-9b96e129-9725-401b-ac34-2feb990202a0](https://user-images.githubusercontent.com/107632780/229646232-19bbafea-ca96-4b36-ad5d-1d64c00d667c.gif)

## Invalid Code Review Request

## You have submitted a project, that doesn't have a proper customized readme,  Please remove all the comments and personalize the readme for this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-14 20:50 UTC, V-Blaze requested changes
## Hi @kamranasif506 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![giphy](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


## Highlights
- Correct data inserted into the database✔✔
- Queries are written correctly :heavy_check_mark: 
- Screenshots show correct results :heavy_check_mark: 

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-14 20:50 UTC, V-Blaze commented on README.md
- You have done great so far customizing your readme, but there are few changes you still need to make. :+1: :+1: 
- [ ] Looking at the screenshot below, you can see you still have some placeholder comments on the readme, you are required to remove them all as they are just there to guide you. :+1: :+1: 

- - Screenshot:
![Selection_002](https://github.com/kamranasif506/Vet-Clinic/assets/107632780/a5900596-194a-4ddf-8b6e-e96b023830d0)

2023-08-14 20:50 UTC, V-Blaze commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] The license link leads to a 404 error page, I'll suggest you add a LICENSE file and link it correctly. :+1: :+1: 

- - Screenshot:
![Screenshot from 2023-08-14 21-42-39](https://github.com/kamranasif506/Vet-Clinic/assets/107632780/95035cfb-be6b-4950-84bc-fd985043f88d)

2023-08-15 03:46 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi @kamranasif506 

Good job for implementing the suggested changes💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Table is created
-  ✅ Screenshots are added 
-  ✅ Successful queries

## Optional suggestions ❕

_Please go through the comments under review_

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-15 03:46 UTC, KanzaTahreem commented on README.md
- [OPTIONAL] Good job for implementing the requested changes 🥇  I've noticed that the **_Getting Started_** section is currently missing from your README. I highly recommend adding it to provide users with a clear starting point. For reference, you can take a look at  [this README](https://github.com/KanzaTahreem/Vet-Clinic-Database) ⛏✨

2023-08-15 04:08 UTC, merged